In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0


In [4]:
#!nvidia-smi
# The above is the line to run, if you want to know what you're GPU status is and all the other information regarding the running GPU,
# As this notebook currently is run on my local machine - MacBook, there is no GPU involved.

## Introduction to Tensors

### Creating Tensors

In [5]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# If we want to get the tensor back as a Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [14]:
#MATRIX
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [3,4,5],
                      [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [23]:
TENSOR[0][1]

tensor([3, 4, 5])

### Random Tensors

Why Random tensors?

Random tensors are important because the way NN learns is that they start with tensors with random numers and then adjust those random numbers to better represent the data

In [31]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0972, 0.1382, 0.2515, 0.6772],
        [0.4123, 0.8749, 0.3003, 0.0031],
        [0.1733, 0.1553, 0.1235, 0.3629]])

In [32]:
random_tensor.ndim

2

In [34]:
# Create a random toensor with similar shape to image tensor
random_image_size_tensor = torch.rand(224,224,3) # heigh, width and color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [35]:
# Create a tensor of all zeroes

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
ones.dtype
# the default datatype of torch tensors is float, unless specified to be an integer

torch.float32

### Range of tensors and tensors-like

In [43]:
# Use torch.arange()
one_to_ten = torch.arange(0,10)
one_to_ten_step = torch.arange(0,10,step=2)
print(one_to_ten)
print(one_to_ten_step)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [44]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [48]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #you can change the data type which you want, maybe torch.float16
                               device=None, #This is used if you have a GPU/ CPU
                               requires_grad=False) #This is used if you want the tensor to update automatically, when sent as a parameter tensor into a DL model
float_32_tensor

tensor([3., 6., 9.])

In [51]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
print(float_16_tensor.device)

cpu
